server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://localhost:9090/demo
          predicates:
            - Path=/demo
            - Method=GET
#          filters:
#             TokenRelay=

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9000/login/oauth2/code/gateway
            scope:
              - openid

        provider:
          spring:
              issuer-uri: http://localhost:8080
