server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          myoauth2:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/myoauth2
            scope:
              - openid
        provider:
          spring:
            issuer-uri: http://localhost:8080